name: FireTV Card
description: 📺 FireTV Remote Card
type: lovelace
keywords:
  - firetvcard
  - remote
  - firetv
  - amazon
  - television
author:
  name: mar_robHD
license: Apache License, Version 2.0
files:
  - firetv-card.js
  - firetv-card-editor.js
